### ISSUE TITLE
проект не инициализируется и не запускается описанным способом

### ISSUE THREAD

**Issue by rptl8sr** [VaDKustiK/yandex-golang-course#1]
`go mod tidy`
не сработает, если нет файла go.mod (его надо оставлять в гите, это важный и нужный файл)

`go run main.go`
выдаст ошибку
`./main.go:22:10: undefined: CalcRequest
./main.go:28:17: undefined: Calc
./main.go:34:10: undefined: CalcResponse`

нормально запустить проект можно так
`go mod init github.com/VaDKustiK/yandex-golang-course`
`go run .`

**Comment by VaDKustiK** [comment]
fixed

**Comment by rptl8sr** [comment]
Ага, работает!
